### ISSUE TITLE
set up travis for this

### ISSUE THREAD

**Issue by ltalirz** [materialscloud-org/tools-barebone#2]

**Comment by kjappelbaum** [comment]
I think github actions could work nice for this and we can see how we can use workflow we use for the oxidation state here. 

I think I have also a few notes to improve the readme. Will add all this asap.

**Comment by ltalirz** [comment]
> I think github actions could work nice for this and we can see how we can use workflow we use for the oxidation state here.

If you're willing to make the PR - even better!
This would be very valuable

> I think I have also a few notes to improve the readme. Will add all this asap.

Great, thanks a lot!

I'll also get PR #1 merged which is super important for debugging - can't believe nobody got round to fixing this. I should discuss with Giovanni at some point who should take control of the tools barebone repo.

**Comment by ltalirz** [comment]
fixed in #7
